# Generated by Django 3.0.5 on 2020-05-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=50)),
                ('drop_location', models.CharField(max_length=50)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('fare', models.IntegerField()),
                ('book_date', models.DateField()),
                ('book_field', models.DateField()),
            ],
        ),
    ]
