# Generated by Django 3.0.5 on 2020-05-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0004_auto_20200523_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
