# Generated by Django 3.0.5 on 2020-05-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0005_auto_20200523_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_field',
            field=models.CharField(default="", max_length=50),
        ),
    ]
