# Generated by Django 3.0.5 on 2020-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0006_book_book_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_field',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
