# Generated by Django 3.0.5 on 2020-05-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0007_auto_20200523_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_field',
        ),
    ]
