# Generated by Django 3.0.5 on 2020-05-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0012_auto_20200523_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='drop_location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='from_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pickup_location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='to_time',
            field=models.TimeField(default='20:00'),
        ),
    ]
