# Generated by Django 3.0.5 on 2020-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0013_auto_20200523_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fare',
            field=models.IntegerField(default=0),
        ),
    ]
