# Generated by Django 3.0.5 on 2020-05-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookride', '0014_auto_20200523_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(default='2020-05-23'),
        ),
    ]
